version: "3"
services:
  db:
    build: .
    image: postgres
    restart: always
    volumes: 
        - "pgdata:/var/lib/postgresql/data"
    ports:
        - "5432:5432"
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pqpass'
      POSTGRES_DB: 'postgres' 
volumes: 
    pgdata:

         
